name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    name: Testing (Node ${{ matrix.node-version }})

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20.x

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 8

      - uses: actions/setup-node@v3
        name: Setup Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Cache PNPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # This is needed for nx affected to work when CI is running on a PR
      - uses: nrwl/nx-set-shas@v3
        name: Set NX's SHAs

      - name: Run tests
        run: |
          npx nx affected -t lint,test,build --parallel=3 --configuration=ci --code-coverage
