name: CI - integration test pnpm

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: NX
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    with:
      node-version: 20.x
      pnpm-version: 8.15.0
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3

  agents:
    name: NX Cloud Agent
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    with:
      node-version: 20.x
      pnpm-version: 8.15.0
      number-of-agents: 3
